/* BLOODLINE BRAWL — AUDIO V1 */
(()=>{
 if(window.__bbAudioV1)return;window.__bbAudioV1=1;
 const AC=window.AudioContext||window.webkitAudioContext;if(!AC)return;
 const A={c:null,m:null,mu:null,s:null,a:null,on:false,track:null,timer:null,step:0,next:0,amb:[],last:{},v:{master:+(localStorage.bbMaster??.82),music:+(localStorage.bbMusic??.30),sfx:+(localStorage.bbSfx??.8)}};
 const hz=m=>440*2**((m-69)/12), ok=(k,g=50)=>{const n=performance.now();if(A.last[k]&&n-A.last[k]<g)return 0;A.last[k]=n;return 1};
 function init(){if(A.c)return;const c=A.c=new AC();A.m=c.createGain();A.mu=c.createGain();A.s=c.createGain();A.a=c.createGain();A.mu.connect(A.m);A.s.connect(A.m);A.a.connect(A.m);A.m.connect(c.destination);vol()}
 function vol(){if(!A.c)return;const t=A.c.currentTime;A.m.gain.setTargetAtTime(A.v.master,t,.02);A.mu.gain.setTargetAtTime(A.v.music,t,.02);A.s.gain.setTargetAtTime(A.v.sfx,t,.02);A.a.gain.setTargetAtTime(Math.min(.18,A.v.music*.5),t,.03)}
 function unlock(){init();A.on=true;if(A.c.state==='suspended')A.c.resume().catch(()=>{});sync()}
 function tone(f,d=.1,v=.07,type='square',to=0,dest=0,when=0){if(!A.on)return;const c=A.c,t=Math.max(c.currentTime,when||c.currentTime),e=t+d,o=c.createOscillator(),g=c.createGain();o.type=type;o.frequency.setValueAtTime(Math.max(20,f),t);if(to)o.frequency.exponentialRampToValueAtTime(Math.max(20,to),e);g.gain.setValueAtTime(.0001,t);g.gain.exponentialRampToValueAtTime(v,t+.004);g.gain.exponentialRampToValueAtTime(.0001,e);o.connect(g);g.connect(dest||A.s);o.start(t);o.stop(e+.02)}
 function noise(d=.1,v=.08,lo=100,hi=5000,dest=0,when=0){if(!A.on)return;const c=A.c,t=Math.max(c.currentTime,when||c.currentTime),b=c.createBuffer(1,c.sampleRate*d,c.sampleRate),x=b.getChannelData(0);for(let i=0;i<x.length;i++)x[i]=Math.random()*2-1;const q=c.createBufferSource(),hp=c.createBiquadFilter(),lp=c.createBiquadFilter(),g=c.createGain();q.buffer=b;hp.type='highpass';hp.frequency.value=lo;lp.type='lowpass';lp.frequency.value=hi;g.gain.setValueAtTime(v,t);g.gain.exponentialRampToValueAtTime(.0001,t+d);q.connect(hp);hp.connect(lp);lp.connect(g);g.connect(dest||A.s);q.start(t)}
 const F={
 hover:()=>tone(560,.035,.035,'square',700),select:()=>{const t=A.c.currentTime;tone(330,.06,.07,'square',470,0,t);tone(660,.07,.045,'square',880,0,t+.035)},back:()=>tone(440,.08,.06,'triangle',240),random:()=>tone(700+Math.random()*250,.03,.04),
 swing:()=>{noise(.09,.09,900,7000);tone(210,.09,.045,'triangle',110)},hit:()=>{noise(.1,.15,80,2600);tone(120,.11,.12,'sine',58)},block:()=>{noise(.07,.07,1300,6500);tone(900,.1,.07,'triangle',500)},jump:()=>tone(150,.13,.065,'triangle',330),land:()=>{noise(.07,.06,40,700);tone(82,.08,.05,'sine',50)},
 special:()=>tone(250,.14,.075,'sawtooth',520),ultimate:()=>{noise(.35,.07,70,2300);tone(74,.38,.13,'sawtooth',148)},ko:()=>{const t=A.c.currentTime;[62,58,50,43].forEach((m,i)=>tone(hz(m),.2,.1,'sawtooth',hz(m-4),0,t+i*.11))},ready:()=>tone(hz(52),.12,.07),fight:()=>{const t=A.c.currentTime;[64,67,71].forEach((m,i)=>tone(hz(m),.13,.07,'square',0,0,t+i*.04))},
 ladder:()=>{noise(.22,.1,350,4300);tone(115,.25,.09,'square',72)},deer:()=>{tone(145,.28,.1,'sawtooth',72);tone(188,.21,.045,'square',90)},bite:()=>{noise(.08,.11,220,3200);tone(135,.1,.1,'square',66)},chair:()=>{noise(.16,.12,100,2400);tone(96,.18,.11,'triangle',54)},paint:()=>{noise(.14,.055,130,1000);tone(210,.14,.05,'sine',135)},pills:()=>{const t=A.c.currentTime;for(let i=0;i<5;i++)tone(900+Math.random()*900,.02,.035,'square',0,0,t+i*.025)},yarn:()=>{const t=A.c.currentTime;for(let i=0;i<4;i++)tone(390+i*45,.06,.035,'triangle',0,0,t+i*.03)},golf:()=>{noise(.13,.08,900,8000);tone(1180,.07,.055,'triangle',760)},plates:()=>{const t=A.c.currentTime;[1120,1480,1760].forEach((f,i)=>tone(f,.12,.04,'triangle',f*.72,0,t+i*.02))},glitch:()=>{const t=A.c.currentTime;for(let i=0;i<5;i++)tone(i%2?760:280,.03,.035,'square',0,0,t+i*.03)},breath:()=>{noise(.24,.08,300,2600);tone(90,.27,.045,'sine',55)}
 };
 function play(k,g=45){if(A.on&&F[k]&&ok(k,g))F[k]()}
 function chr(side){try{return side===1?player1Character:player2Character}catch(_){return null}}
 function act(c,k){if(k==='melee')return play(c==='brendan'?'golf':'swing',70);if(k==='special')return play(({grandaddy:'ladder',connor:'paint',shannan:'glitch',sean:'plates',martin:'breath',kelly:'pills',leah:'yarn'})[c]||'special',90);play('ultimate',150);const e=({sean:'deer',martin:'bite',grandmommy:'chair',connor:'paint',kelly:'breath',leah:'yarn'})[c];if(e)setTimeout(()=>play(e,140),80)}
 const T={title:{b:112,bs:[40,40,47,40,43,43,47,43,45,45,52,47,43,47,40,35],ld:[64,null,67,null,71,null,67,64,62,null,64,67,71,69,67,null],rt:[52,55,57,55]},select:{b:132,bs:[45,45,52,45,48,48,52,48,50,50,57,52,48,52,45,40],ld:[69,72,76,72,69,72,77,76,72,74,76,79,77,76,72,69],rt:[57,60,62,60]}};
 function step(th,i,t){const e=(60/th.b)/2,b=th.bs[i],l=th.ld[i];if(b!=null)tone(hz(b),e*.7,.055,'square',0,A.mu,t);if(l!=null)tone(hz(l),e*.45,A.track==='title'?.036:.044,'triangle',0,A.mu,t);if(i%4===0){const r=th.rt[(i/4)%4];[r,r+4,r+7].forEach((m,j)=>tone(hz(m),(60/th.b)*1.3,.013,'sine',0,A.mu,t+j*.005))}}
 function look(){if(!A.on||!A.track)return;const th=T[A.track],e=(60/th.b)/2;while(A.next<A.c.currentTime+.28){step(th,A.step,A.next);A.next+=e;A.step=(A.step+1)%16}}
 function music(n){if(!A.on||A.track===n)return;if(A.timer)clearInterval(A.timer);A.track=n;A.step=0;A.next=A.c.currentTime+.04;look();A.timer=setInterval(look,90)}
 function stop(){if(A.timer)clearInterval(A.timer);A.timer=null;A.track=null}
 function clearAmb(){A.amb.forEach(n=>{try{n.stop?.()}catch(_){ }try{n.disconnect?.()}catch(_){ }});A.amb=[]}
 function ambNoise(lo,hi,v){const c=A.c,b=c.createBuffer(1,c.sampleRate*2,c.sampleRate),x=b.getChannelData(0);for(let i=0;i<x.length;i++)x[i]=Math.random()*2-1;const s=c.createBufferSource(),hp=c.createBiquadFilter(),lp=c.createBiquadFilter(),g=c.createGain();s.buffer=b;s.loop=true;hp.type='highpass';hp.frequency.value=lo;lp.type='lowpass';lp.frequency.value=hi;g.gain.value=v;s.connect(hp);hp.connect(lp);lp.connect(g);g.connect(A.a);s.start();A.amb.push(s,hp,lp,g)}
 function map(){try{return selectedMap||'virginia'}catch(_){return document.querySelector('.map-card.selected')?.dataset.map||'virginia'}}
 function ambience(){clearAmb();const m=map();if(m==='westhampton'){ambNoise(100,1250,.07);ambNoise(1100,6000,.014)}else if(m==='virginia')ambNoise(180,1800,.024);else if(m==='newcanaan'){ambNoise(180,1050,.022);ambNoise(1100,3800,.008)}else ambNoise(120,1500,.026)}
 function sync(){if(!A.on)return;const id=document.querySelector('.screen.active')?.id;if(id==='titleScreen'){clearAmb();music('title')}else if(['selectScreen','challengeScreen','mapScreen'].includes(id)){clearAmb();music('select')}else if(id==='fightScreen'){stop();ambience()}}
 const css=document.createElement('style');css.textContent=`.bb-sound{position:fixed;top:10px;right:12px;z-index:9999;font:900 10px Arial}.bb-sound button{padding:7px 10px;color:#fff;background:#09131ddd;border:2px solid #637789;border-radius:6px;cursor:pointer}.bb-sound-panel{position:absolute;right:0;top:37px;width:210px;padding:9px 11px;background:#09131df5;border:2px solid #637789;border-radius:7px}.bb-sound-panel.hide{display:none}.bb-sound-row{display:grid;grid-template-columns:52px 1fr 28px;gap:6px;align-items:center;margin:6px 0;color:#fff}.bb-sound-row input{width:100%;accent-color:#ffd52a}.bb-sound-val{color:#9edcff;text-align:right}`;document.head.appendChild(css);
 const box=document.createElement('div');box.className='bb-sound';box.innerHTML=`<button>SOUND</button><div class="bb-sound-panel hide"><div class="bb-sound-row">MASTER<input data-v="master" type="range" min="0" max="100"><span class="bb-sound-val"></span></div><div class="bb-sound-row">MUSIC<input data-v="music" type="range" min="0" max="100"><span class="bb-sound-val"></span></div><div class="bb-sound-row">SFX<input data-v="sfx" type="range" min="0" max="100"><span class="bb-sound-val"></span></div></div>`;document.body.appendChild(box);const panel=box.querySelector('.bb-sound-panel');function ui(){box.querySelectorAll('input').forEach(i=>{const v=A.v[i.dataset.v];i.value=Math.round(v*100);i.nextElementSibling.textContent=i.value})}ui();box.querySelector('button').onclick=e=>{e.stopPropagation();unlock();panel.classList.toggle('hide');play('select',60)};box.oninput=e=>{const i=e.target.closest('input');if(!i)return;unlock();A.v[i.dataset.v]=+i.value/100;localStorage['bb'+i.dataset.v[0].toUpperCase()+i.dataset.v.slice(1)]=A.v[i.dataset.v];vol();ui()};
 let hov=null;document.addEventListener('pointerover',e=>{const b=e.target.closest('button');if(!b||b===hov)return;hov=b;if(A.on)play('hover',30)},true);document.addEventListener('pointerout',e=>{if(e.target.closest('button')===hov)hov=null},true);document.addEventListener('pointerdown',e=>{if(!e.target.closest('.bb-sound'))unlock()},{capture:true,passive:true});document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b||b.closest('.bb-sound'))return;play(['backToTitleButton','backToFighterButton','challengeBackButton'].includes(b.id)?'back':'select',60);if(b.classList.contains('bb-random-card')){let n=0,q=setInterval(()=>{play('random',15);if(++n>6)clearInterval(q)},50)}setTimeout(sync,35)},true);
 document.addEventListener('keydown',e=>{if(e.repeat)return;unlock();if(!document.getElementById('fightScreen')?.classList.contains('active'))return;const k=e.key.toLowerCase();if(k==='w'||e.key==='ArrowUp')play('jump',80);if(k==='q'||k==='i')play('block',80);if(k==='r')act(chr(1),'melee');if(k==='j')act(chr(2),'melee');if(k==='e')act(chr(1),'special');if(k==='k')act(chr(2),'special');if(k==='f')act(chr(1),'ultimate');if(k==='l')act(chr(2),'ultimate')},true);
 function hp(id,key){const b=document.getElementById(id);if(!b)return;let old=100;new MutationObserver(()=>{const n=parseFloat(b.style.width||'100');if(n<old-.05){play('hit',40);if(n<=.05)setTimeout(()=>play('ko',800),50)}old=n}).observe(b,{attributes:true,attributeFilter:['style']})}hp('player1Health','p1');hp('player2Health','p2');
 const w=document.getElementById('battleIntroWord');if(w){let o='';new MutationObserver(()=>{const t=w.textContent.toUpperCase();if(t===o)return;o=t;if(t.includes('READY'))play('ready',250);if(t.includes('FIGHT'))play('fight',250)}).observe(w,{childList:true,subtree:true,characterData:true})}
 const ef=document.getElementById('effects');if(ef)new MutationObserver(rs=>{for(const r of rs)for(const n of r.addedNodes){if(!(n instanceof Element))continue;const s=`${n.className} ${n.innerHTML}`;if(s.includes('zombie-deer'))play('deer',200);else if(s.includes('clyde'))play('bite',180);else if(s.includes('yoga-chair'))play('chair',180);else if(s.includes('bb-ladder-rig'))play('ladder',180);else if(s.includes('bb-pill'))play('pills',150);else if(s.includes('bb-yarn'))play('yarn',150);else if(s.includes('paint'))play('paint',150)}}).observe(ef,{childList:true,subtree:true});
 window.BloodlineAudio={play,sync,music,stop};
})();
