/* =====================================================
   BLOODLINE BRAWL — ALICE / LEO / BARRETT
   Additive character expansion only.
   Preserves the current game and routes only these three fighters.
===================================================== */

(() => {
  if (window.__bbToddlerTrioV1Loaded) return;
  window.__bbToddlerTrioV1Loaded = true;

  const TODDLERS = ["alice", "leo", "barrett"];
  const style = document.createElement("style");
  style.textContent = `
    /* ---------- toddler proportions ---------- */
    .bb-toddler{position:relative;width:88px;transform-origin:bottom center}
    .alice-model,.leo-model{height:132px}.barrett-model{width:78px;height:99px}
    .title-character-space .bb-toddler{transform:scale(1.05)!important;transform-origin:bottom center!important}
    .bb-select-overhauled .card-model-holder .bb-toddler{transform:scale(.47)!important;transform-origin:bottom center!important}
    .bb-detail-preview .bb-toddler{transform:scale(1.02)!important;transform-origin:bottom center!important}
    .challenge-choice-model .bb-toddler{transform:scale(.68)!important;transform-origin:bottom center!important}
    .bb-toddler-face{position:absolute;background:#efc09b;border:3px solid #111;border-radius:7px;z-index:8}
    .alice-model .bb-toddler-face,.leo-model .bb-toddler-face{width:42px;height:39px;left:23px;top:22px}
    .barrett-model .bb-toddler-face{width:37px;height:34px;left:20px;top:17px;border-radius:8px}
    .bb-toddler-eye{position:absolute;top:12px;width:5px;height:7px;background:#111}.bb-toddler-eye.l{left:8px}.bb-toddler-eye.r{right:8px}.barrett-model .bb-toddler-eye{top:10px;height:6px}
    .bb-toddler-mouth{position:absolute;left:50%;bottom:6px;width:13px;height:5px;transform:translateX(-50%);border-bottom:3px solid #111;border-radius:50%}
    .bb-toddler-arm{position:absolute;background:#efc09b;border:3px solid #111;z-index:10;transform-origin:50% 5px}
    .alice-model .bb-toddler-arm,.leo-model .bb-toddler-arm{top:66px;width:12px;height:38px}.alice-model .bb-toddler-arm.l,.leo-model .bb-toddler-arm.l{left:10px}.alice-model .bb-toddler-arm.r,.leo-model .bb-toddler-arm.r{right:10px}
    .barrett-model .bb-toddler-arm{top:51px;width:11px;height:29px}.barrett-model .bb-toddler-arm.l{left:8px}.barrett-model .bb-toddler-arm.r{right:8px}
    .bb-toddler-leg{position:absolute;border:3px solid #111;z-index:4}.alice-model .bb-toddler-leg,.leo-model .bb-toddler-leg{top:96px;width:18px;height:31px}.alice-model .bb-toddler-leg.l,.leo-model .bb-toddler-leg.l{left:23px}.alice-model .bb-toddler-leg.r,.leo-model .bb-toddler-leg.r{right:23px}
    .barrett-model .bb-toddler-leg{top:73px;width:15px;height:20px;background:#315b93}.barrett-model .bb-toddler-leg.l{left:19px}.barrett-model .bb-toddler-leg.r{right:19px}
    .bb-toddler-shoe{position:absolute;background:#f7f7f7;border:3px solid #111;z-index:12}.alice-model .bb-toddler-shoe,.leo-model .bb-toddler-shoe{top:122px;width:23px;height:10px}.alice-model .bb-toddler-shoe.l,.leo-model .bb-toddler-shoe.l{left:18px}.alice-model .bb-toddler-shoe.r,.leo-model .bb-toddler-shoe.r{right:18px}
    .barrett-model .bb-toddler-shoe{top:90px;width:19px;height:9px}.barrett-model .bb-toddler-shoe.l{left:15px}.barrett-model .bb-toddler-shoe.r{right:15px}

    /* ---------- Alice ---------- */
    .bb-alice-hair{position:absolute;left:20px;top:7px;width:49px;height:28px;background:#6a4328;border:3px solid #111;border-radius:15px 15px 7px 7px;z-index:6}.bb-alice-hair:before,.bb-alice-hair:after{content:"";position:absolute;top:16px;width:9px;height:27px;background:#6a4328;border-bottom:3px solid #111}.bb-alice-hair:before{left:-5px;border-left:3px solid #111}.bb-alice-hair:after{right:-5px;border-right:3px solid #111}
    .bb-alice-shirt{position:absolute;left:18px;top:59px;width:52px;height:43px;background:#ed67a4;border:3px solid #111;border-radius:8px 8px 4px 4px;z-index:5}.alice-model .bb-toddler-leg{background:#f6f6f6}
    .bb-fairy-wand{position:absolute;left:3px;top:11px;width:5px;height:47px;background:#e7c66f;border:2px solid #111;transform:rotate(18deg);transform-origin:bottom center;z-index:25}.bb-fairy-wand:before{content:"★";position:absolute;left:-9px;top:-18px;color:#ffd95b;font:900 22px Arial;text-shadow:1px 1px #111}
    .alice-model.bb-alice-basic .bb-toddler-arm.r{animation:bbAliceBonk .44s ease-out 1}@keyframes bbAliceBonk{0%{transform:rotate(0)}30%{transform:rotate(-32deg)}70%{transform:rotate(44deg)}100%{transform:rotate(2deg)}}
    .bb-hand-lollipop{position:absolute;left:-5px;top:0;width:29px;height:54px;z-index:28;transform:rotate(-15deg)}
    .bb-hand-lollipop:before,.bb-grape-lollipop:before,.bb-giant-lollipop:before,.bb-victory-lollipop:before{content:"";position:absolute;border-radius:50%;background:radial-gradient(circle at 34% 31%,#c994ff 0 12%,#7d35b8 13% 62%,#4e1d78 63% 100%);border:3px solid #2b123d;box-shadow:inset -5px -5px 0 rgba(0,0,0,.12)}
    .bb-hand-lollipop:before{left:0;top:0;width:26px;height:26px}.bb-hand-lollipop:after,.bb-grape-lollipop:after,.bb-giant-lollipop:after,.bb-victory-lollipop:after{content:"";position:absolute;background:#f0e6d7;border:2px solid #4a3a30;transform-origin:top center}.bb-hand-lollipop:after{left:12px;top:24px;width:4px;height:31px}
    .bb-grape-lollipop{position:absolute;width:43px;height:72px;z-index:255;pointer-events:none;animation:bbLollipopSpin .28s linear infinite}.bb-grape-lollipop:before{left:2px;top:0;width:38px;height:38px}.bb-grape-lollipop:after{left:19px;top:34px;width:5px;height:38px}@keyframes bbLollipopSpin{to{transform:rotate(360deg)}}
    .bb-magic-star{position:absolute;width:8px;height:8px;background:#ffd95b;clip-path:polygon(50% 0,61% 36%,100% 50%,61% 64%,50% 100%,39% 64%,0 50%,39% 36%);z-index:330;animation:bbMagicPop .55s ease-out forwards}@keyframes bbMagicPop{0%{transform:translate(0,0) scale(.2);opacity:0}35%{opacity:1}100%{transform:translate(var(--sx),var(--sy)) rotate(110deg) scale(.7);opacity:0}}
    .bb-alice-wings{position:absolute;left:8px;top:41px;width:72px;height:50px;z-index:1}.bb-alice-wings:before,.bb-alice-wings:after{content:"";position:absolute;top:0;width:34px;height:46px;border:3px solid #874dcc;background:rgba(218,177,255,.62);border-radius:60% 35% 65% 38%;box-shadow:0 0 10px #dba9ff}.bb-alice-wings:before{left:0;transform:rotate(-24deg)}.bb-alice-wings:after{right:0;transform:scaleX(-1) rotate(-24deg)}
    .bb-princess-crown{position:absolute;left:29px;top:-7px;width:31px;height:19px;background:#ffd84c;border:3px solid #5a3a12;clip-path:polygon(0 100%,0 42%,20% 65%,33% 0,50% 58%,69% 0,82% 66%,100% 40%,100% 100%);z-index:30;filter:drop-shadow(0 2px 0 #0005)}
    .bb-alice-glow{position:absolute;left:-7px;top:-5px;width:102px;height:140px;border-radius:45%;border:4px dashed rgba(235,176,255,.8);box-shadow:0 0 22px rgba(199,91,255,.7);animation:bbMagicOrbit .7s linear infinite;z-index:0}@keyframes bbMagicOrbit{to{transform:rotate(360deg)}}
    .bb-giant-lollipop{position:absolute;width:150px;height:255px;z-index:340;pointer-events:none;transform-origin:50% 78%;filter:drop-shadow(8px 10px 0 rgba(0,0,0,.25))}.bb-giant-lollipop:before{left:0;top:0;width:142px;height:142px;border-width:6px}.bb-giant-lollipop:after{left:68px;top:128px;width:9px;height:132px;border-width:3px}

    /* ---------- Leo ---------- */
    .bb-leo-hair{position:absolute;left:21px;top:8px;width:47px;height:24px;background:#664127;border:3px solid #111;border-radius:13px 13px 5px 5px;z-index:10}.bb-leo-shirt{position:absolute;left:18px;top:59px;width:52px;height:43px;background:#3276bc;border:3px solid #111;border-radius:8px 8px 4px 4px;z-index:5}.leo-model .bb-toddler-leg{background:#4f8b42}
    .bb-dino-claw{position:absolute;left:-5px;top:25px;width:19px;height:15px;z-index:22}.bb-dino-claw:before,.bb-dino-claw:after{content:"";position:absolute;top:0;width:4px;height:13px;background:#f1e4c2;border:1px solid #111;clip-path:polygon(0 0,100% 0,50% 100%)}.bb-dino-claw:before{left:2px;transform:rotate(12deg)}.bb-dino-claw:after{right:2px;transform:rotate(-12deg)}
    .leo-model.bb-leo-swipe1 .bb-toddler-arm.r{animation:bbLeoSwipeR .24s ease-out}.leo-model.bb-leo-swipe2 .bb-toddler-arm.l{animation:bbLeoSwipeL .24s ease-out}@keyframes bbLeoSwipeR{0%{transform:rotate(0)}35%{transform:rotate(-25deg) translateX(-3px)}72%{transform:rotate(34deg) translateX(9px)}100%{transform:rotate(2deg)}}@keyframes bbLeoSwipeL{0%{transform:rotate(0)}35%{transform:rotate(24deg) translateX(3px)}72%{transform:rotate(-32deg) translateX(-9px)}100%{transform:rotate(-2deg)}}
    .bb-claw-trail{position:absolute;width:47px;height:34px;border-top:4px solid #bff36a;border-bottom:4px solid #bff36a;border-radius:50%;z-index:300;animation:bbClawTrail .28s ease-out forwards}.bb-claw-trail:after{content:"";position:absolute;left:3px;right:3px;top:12px;border-top:4px solid #e5ff99;border-radius:50%}@keyframes bbClawTrail{from{transform:scale(.45) rotate(-17deg);opacity:0}45%{opacity:1}to{transform:scale(1.25) rotate(12deg);opacity:0}}
    .leo-model.bb-leo-stomp{animation:bbLeoStomp .68s ease-in-out}@keyframes bbLeoStomp{0%,100%{transform:translateY(0)}30%{transform:translateY(-17px)}57%{transform:translateY(-21px)}75%{transform:translateY(4px)}}
    .bb-dino-foot{position:absolute;width:102px;height:70px;z-index:300;pointer-events:none;transform-origin:center bottom;animation:bbFootSlam .38s ease-in forwards}.bb-dino-foot:before{content:"";position:absolute;left:25px;top:19px;width:54px;height:43px;background:#72a653;border:4px solid #24351c;border-radius:45% 45% 55% 55%}.bb-dino-foot:after{content:"";position:absolute;left:8px;top:4px;width:86px;height:34px;background:radial-gradient(ellipse at 18% 72%,#edf0c7 0 9px,transparent 10px),radial-gradient(ellipse at 50% 55%,#edf0c7 0 10px,transparent 11px),radial-gradient(ellipse at 82% 72%,#edf0c7 0 9px,transparent 10px)}@keyframes bbFootSlam{0%{transform:translateY(-85px) scale(1.18);opacity:0}55%{opacity:1}100%{transform:translateY(0) scale(1)}}
    .bb-ground-shock{position:absolute;width:145px;height:28px;border:5px solid #d5ee8b;border-radius:50%;z-index:280;animation:bbShock .45s ease-out forwards}@keyframes bbShock{from{transform:scale(.25);opacity:1}to{transform:scale(1.4);opacity:0}}

    /* distinct full dinosaur models */
    .bb-cine-dino{position:absolute;width:180px;height:120px;z-index:335;pointer-events:none;filter:drop-shadow(6px 7px 0 rgba(0,0,0,.26));transform-origin:center bottom}.bb-cine-dino .body{position:absolute;left:42px;top:43px;width:96px;height:51px;background:#668f4c;border:4px solid #26351f;border-radius:48% 52% 43% 45%}.bb-cine-dino .tail{position:absolute;left:4px;top:54px;width:60px;height:19px;background:#668f4c;border:4px solid #26351f;border-radius:50%;transform:rotate(-9deg)}.bb-cine-dino .leg{position:absolute;top:86px;width:17px;height:31px;background:#52773d;border:4px solid #26351f}.bb-cine-dino .leg.a{left:62px}.bb-cine-dino .leg.b{left:112px}
    .bb-triceratops .head{position:absolute;left:127px;top:35px;width:48px;height:45px;background:#759f58;border:4px solid #26351f;border-radius:45%}.bb-triceratops .frill{position:absolute;left:113px;top:23px;width:49px;height:59px;background:#8ab468;border:4px solid #26351f;clip-path:polygon(100% 18%,79% 39%,100% 53%,73% 65%,92% 92%,47% 76%,12% 100%,16% 58%,0 33%,39% 31%,45% 0)}.bb-triceratops .horn{position:absolute;width:29px;height:8px;background:#eee0b6;border:2px solid #4b402d;clip-path:polygon(0 50%,100% 0,100% 100%);z-index:7}.bb-triceratops .horn.h1{left:159px;top:36px}.bb-triceratops .horn.h2{left:153px;top:56px;transform:rotate(7deg)}
    .bb-trex .body{background:#658b45}.bb-trex .head{position:absolute;left:125px;top:33px;width:55px;height:39px;background:#709a4c;border:4px solid #26351f;border-radius:43% 51% 35% 43%;z-index:6}.bb-trex .jaw{position:absolute;left:139px;top:62px;width:42px;height:17px;background:#5f843f;border:4px solid #26351f;border-radius:0 0 45% 48%;transform-origin:left top;animation:bbTrexBite .42s ease-in-out infinite}.bb-trex .jaw:after{content:"";position:absolute;left:5px;top:-4px;width:28px;height:7px;background:repeating-linear-gradient(90deg,#f4ead1 0 4px,transparent 4px 7px)}.bb-trex .tinyarm{position:absolute;left:125px;top:69px;width:24px;height:7px;background:#52773d;border:3px solid #26351f;transform:rotate(22deg)}@keyframes bbTrexBite{50%{transform:rotate(19deg)}}
    .bb-anky .body{left:39px;top:48px;width:108px;height:47px;background:#77844a}.bb-anky .armor{position:absolute;left:45px;top:38px;width:96px;height:28px;background:repeating-linear-gradient(90deg,#9b9b63 0 15px,#777d49 15px 28px);border:4px solid #333723;border-radius:55% 55% 20% 20%}.bb-anky .head{position:absolute;left:136px;top:56px;width:38px;height:31px;background:#7e8d52;border:4px solid #333723;border-radius:46%}.bb-anky .clubtail{position:absolute;left:-9px;top:57px;width:62px;height:13px;background:#727e49;border:4px solid #333723;border-radius:50%;transform-origin:right center}.bb-anky .clubtail:before{content:"";position:absolute;left:-13px;top:-10px;width:27px;height:28px;background:#8d9054;border:4px solid #333723;border-radius:42%}

    /* ---------- Barrett ---------- */
    .bb-barrett-hair{position:absolute;left:31px;top:8px;width:18px;height:7px;background:#6b442b;border:2px solid #111;border-radius:50%;z-index:10;transform:rotate(-5deg)}.bb-barrett-hair:before{content:"";position:absolute;left:-4px;top:1px;width:7px;height:4px;background:#6b442b;border-radius:50%}
    .bb-barrett-shirt{position:absolute;left:16px;top:48px;width:46px;height:30px;background:#cb3d36;border:3px solid #111;border-radius:8px 8px 4px 4px;z-index:5}
    .bb-remote{position:absolute;left:-4px;top:13px;width:18px;height:25px;background:#30343a;border:3px solid #111;border-radius:4px;z-index:26}.bb-remote:before{content:"";position:absolute;left:5px;top:4px;width:4px;height:4px;border-radius:50%;background:#e95151;box-shadow:0 8px 0 #67b9ef}.bb-remote:after{content:"";position:absolute;left:8px;top:-13px;width:2px;height:13px;background:#111;transform:rotate(13deg);transform-origin:bottom}.barrett-model.bb-remote-press .bb-toddler-arm.r{animation:bbRemotePress .48s ease-out}@keyframes bbRemotePress{0%,100%{transform:rotate(0)}45%{transform:rotate(-18deg) translateY(-3px)}}
    .barrett-model.bb-headbutt{animation:bbHeadDip .38s ease-out}@keyframes bbHeadDip{0%,100%{transform:rotate(0)}55%{transform:rotate(13deg) translateY(4px)}}.barrett-model.bb-stumble{animation:bbBabyStumble .5s ease-out}@keyframes bbBabyStumble{0%{transform:rotate(0)}30%{transform:rotate(-13deg) translateY(3px)}60%{transform:rotate(9deg)}100%{transform:rotate(0)}}
    .bb-rc-car{position:absolute;width:72px;height:34px;z-index:275;pointer-events:none}.bb-rc-car .body{position:absolute;left:4px;top:6px;width:64px;height:20px;background:#e15047;border:3px solid #111;border-radius:9px 14px 5px 5px}.bb-rc-car .cab{position:absolute;left:24px;top:0;width:29px;height:15px;background:#76b9df;border:3px solid #111;border-radius:9px 9px 2px 2px}.bb-rc-car .wheel{position:absolute;top:22px;width:17px;height:17px;border-radius:50%;background:#242424;border:3px solid #111}.bb-rc-car .wheel.l{left:10px}.bb-rc-car .wheel.r{right:8px}.bb-rc-car .antenna{position:absolute;left:14px;top:-11px;width:2px;height:18px;background:#222;transform:rotate(-18deg)}
    .bb-dust{position:absolute;width:9px;height:9px;border-radius:50%;background:#d7c59e;z-index:300;animation:bbDust .5s ease-out forwards}@keyframes bbDust{to{transform:translate(var(--dx),-22px) scale(1.7);opacity:0}}
    .bb-big-bear-car{position:absolute;width:248px;height:132px;z-index:345;pointer-events:none;filter:drop-shadow(7px 8px 0 #0004)}.bb-big-bear-car .carbody{position:absolute;left:3px;top:61px;width:238px;height:55px;background:linear-gradient(#d84f3f,#972c24);border:5px solid #111;border-radius:27px 30px 12px 12px}.bb-big-bear-car .hood{position:absolute;left:151px;top:52px;width:78px;height:25px;background:#e35a48;border:5px solid #111;border-radius:12px}.bb-big-bear-car .cab{position:absolute;left:55px;top:25px;width:117px;height:64px;background:#78b5d7;border:5px solid #111;border-radius:28px 28px 5px 5px;overflow:hidden}.bb-big-bear-car .wheel{position:absolute;top:99px;width:40px;height:40px;border-radius:50%;background:#222;border:6px solid #111;box-shadow:inset 0 0 0 6px #777}.bb-big-bear-car .wheel.l{left:38px}.bb-big-bear-car .wheel.r{right:35px}
    .bb-bear-head{position:absolute;left:27px;top:7px;width:58px;height:53px;background:#9b6948;border:4px solid #211915;border-radius:47% 47% 43% 43%;z-index:9}.bb-bear-head:before,.bb-bear-head:after{content:"";position:absolute;top:-9px;width:19px;height:19px;background:#9b6948;border:4px solid #211915;border-radius:50%;z-index:-1}.bb-bear-head:before{left:1px}.bb-bear-head:after{right:1px}.bb-bear-eye{position:absolute;top:17px;width:6px;height:6px;border-radius:50%;background:#111}.bb-bear-eye.l{left:14px}.bb-bear-eye.r{right:14px}.bb-bear-muzzle{position:absolute;left:15px;top:29px;width:27px;height:18px;background:#c5926c;border:3px solid #211915;border-radius:50%}.bb-bear-muzzle:after{content:"";position:absolute;left:8px;top:2px;width:8px;height:6px;background:#211915;border-radius:50%}
    .bb-speedline{position:absolute;left:-58px;width:72px;height:5px;background:#fff2be;border-radius:5px;opacity:.85;animation:bbSpeedline .25s linear infinite}.bb-speedline.a{top:42px}.bb-speedline.b{top:65px;animation-delay:-.1s}.bb-speedline.c{top:89px;animation-delay:-.18s}@keyframes bbSpeedline{from{transform:translateX(0) scaleX(.5);opacity:0}50%{opacity:.9}to{transform:translateX(-42px) scaleX(1.2);opacity:0}}

    /* ---------- icons ---------- */
    .bb-icon-lollipop,.bb-icon-crown,.bb-icon-foot,.bb-icon-dinohead,.bb-icon-rc,.bb-icon-bearwheel,.bb-icon-wand,.bb-icon-claw,.bb-icon-headbutt{position:relative;width:34px;height:34px}
    .bb-icon-lollipop:before{content:"";position:absolute;left:6px;top:1px;width:20px;height:20px;border-radius:50%;background:#8438b8;border:3px solid #24122f}.bb-icon-lollipop:after{content:"";position:absolute;left:16px;top:20px;width:4px;height:14px;background:#eee0cc;border:1px solid #4b3b30}
    .bb-icon-crown:before{content:"";position:absolute;left:3px;top:8px;width:28px;height:20px;background:#ffd64b;border:3px solid #4f3511;clip-path:polygon(0 100%,0 38%,21% 63%,34% 0,50% 58%,68% 0,82% 63%,100% 35%,100% 100%)}
    .bb-icon-foot:before{content:"";position:absolute;left:9px;top:12px;width:20px;height:18px;border-radius:50%;background:#79a857;border:2px solid #26351f;box-shadow:-7px -7px 0 -3px #79a857,1px -10px 0 -3px #79a857,9px -6px 0 -3px #79a857}.bb-icon-dinohead:before{content:"";position:absolute;left:4px;top:8px;width:27px;height:21px;background:#6d984d;border:3px solid #26351f;border-radius:50% 35% 42% 45%}.bb-icon-dinohead:after{content:"";position:absolute;right:2px;top:20px;width:18px;height:7px;border-bottom:3px dashed #f5efd7}
    .bb-icon-rc:before{content:"";position:absolute;left:2px;top:11px;width:30px;height:15px;background:#d84b42;border:3px solid #111;border-radius:5px;box-shadow:3px 10px 0 -5px #222,-10px 10px 0 -5px #222}.bb-icon-bearwheel{border:5px solid #303030;border-radius:50%}.bb-icon-bearwheel:before{content:"";position:absolute;left:6px;top:7px;width:14px;height:13px;background:#9b6948;border:2px solid #211915;border-radius:50%;box-shadow:-4px -5px 0 -2px #9b6948,8px -5px 0 -2px #9b6948}
    .bb-icon-wand:before{content:"";position:absolute;left:15px;top:5px;width:4px;height:28px;background:#e7c66f;border:1px solid #111;transform:rotate(25deg)}.bb-icon-wand:after{content:"★";position:absolute;left:5px;top:-3px;color:#ffd95b;font:900 18px Arial;text-shadow:1px 1px #111}.bb-icon-claw:before{content:"";position:absolute;left:5px;top:7px;width:24px;height:20px;border-top:4px solid #dff49e;border-bottom:4px solid #dff49e;border-radius:50%;transform:rotate(-16deg)}.bb-icon-headbutt:before{content:"";position:absolute;left:7px;top:5px;width:20px;height:23px;border-radius:50%;background:#efc09b;border:3px solid #111}

    /* ---------- toddler victory ---------- */
    .bb-toddler-victory{position:absolute;inset:0;z-index:971;pointer-events:none;overflow:hidden}.bb-toddler-banner{position:absolute;left:50%;top:10%;transform:translateX(-50%);font:900 34px Arial,sans-serif;color:#fff;text-shadow:0 4px #111,0 0 18px #ffd84f;white-space:nowrap;z-index:990}.bb-toddler-victor{position:absolute;bottom:28px;transform:translateX(-50%);z-index:982}.bb-toddler-victor>.bb-toddler{position:relative!important;left:0!important;bottom:0!important}
    .bb-alice-twirl{animation:bbAliceTwirl 1.25s ease-in-out 3}@keyframes bbAliceTwirl{0%,100%{transform:translateX(-50%) rotate(0) translateY(0)}35%{transform:translateX(-50%) rotate(-12deg) translateY(-20px)}70%{transform:translateX(-50%) rotate(12deg) translateY(-8px)}}
    .bb-victory-lollipop{position:absolute;left:74%;bottom:88px;width:58px;height:96px;transform:rotate(9deg);z-index:986}.bb-victory-lollipop:before{left:3px;top:0;width:49px;height:49px;border-width:4px}.bb-victory-lollipop:after{left:25px;top:45px;width:6px;height:51px}
    .bb-baby-trex{position:absolute;left:59%;bottom:28px;width:128px;height:87px;z-index:981;filter:drop-shadow(4px 5px 0 #0004);animation:bbBabyRexRoar .75s ease-in-out 5}.bb-baby-trex .body{position:absolute;left:31px;top:35px;width:63px;height:34px;background:#6b984b;border:4px solid #27351f;border-radius:50%}.bb-baby-trex .head{position:absolute;left:80px;top:20px;width:43px;height:33px;background:#73a152;border:4px solid #27351f;border-radius:45%}.bb-baby-trex .jaw{position:absolute;left:89px;top:46px;width:34px;height:12px;background:#628b45;border:3px solid #27351f;transform-origin:left top;animation:bbTrexBite .4s ease-in-out infinite}.bb-baby-trex .tail{position:absolute;left:3px;top:43px;width:43px;height:14px;background:#678f48;border:4px solid #27351f;border-radius:50%;transform:rotate(-9deg)}.bb-baby-trex .leg{position:absolute;top:64px;width:12px;height:21px;background:#54783d;border:3px solid #27351f}.bb-baby-trex .leg.a{left:46px}.bb-baby-trex .leg.b{left:77px}@keyframes bbBabyRexRoar{0%,100%{transform:translateY(0) rotate(0)}50%{transform:translateY(-17px) rotate(-4deg)}}.bb-leo-victor{animation:bbLeoRoar .75s ease-in-out 5}@keyframes bbLeoRoar{0%,100%{transform:translateX(-50%) translateY(0)}50%{transform:translateX(-50%) translateY(-18px) rotate(5deg)}}
    .bb-celeb-car{position:absolute;left:50%;bottom:16px;width:330px;height:180px;transform:translateX(-50%);z-index:980;animation:bbCarBounce .7s ease-in-out 7}.bb-celeb-car .carbody{position:absolute;left:8px;top:85px;width:314px;height:73px;background:linear-gradient(#d94d3d,#9d2d23);border:6px solid #111;border-radius:31px 36px 16px 16px}.bb-celeb-car .cab{position:absolute;left:71px;top:38px;width:184px;height:83px;background:#79afd0;border:6px solid #111;border-radius:35px 35px 6px 6px;overflow:visible}.bb-celeb-car .wheel{position:absolute;top:139px;width:52px;height:52px;border-radius:50%;background:#242424;border:7px solid #111;box-shadow:inset 0 0 0 8px #777}.bb-celeb-car .wheel.l{left:51px}.bb-celeb-car .wheel.r{right:48px}.bb-celeb-bear{position:absolute;left:25px;top:8px;animation:bbHeadNod .58s ease-in-out 8;transform-origin:center bottom}.bb-celeb-barrett{position:absolute;right:22px;top:-4px;width:78px;height:99px;animation:bbHeadNod .58s ease-in-out 8;transform-origin:center bottom}.bb-celeb-barrett>.barrett-model{transform:scale(.58);transform-origin:top center}.bb-king-crown{position:absolute;right:32px;top:-1px;width:34px;height:23px;background:#ffd338;border:3px solid #5a3a12;clip-path:polygon(0 100%,0 42%,18% 64%,31% 0,49% 61%,68% 0,83% 65%,100% 35%,100% 100%);transform:rotate(12deg);z-index:999}@keyframes bbHeadNod{0%,100%{transform:rotate(0)}50%{transform:rotate(11deg) translateY(3px)}}@keyframes bbCarBounce{0%,100%{transform:translateX(-50%) translateY(0)}50%{transform:translateX(-50%) translateY(-8px)}}
    .bb-toddler-shake{animation:bbToddlerShake .36s linear 1}@keyframes bbToddlerShake{0%,100%{transform:translate(0)}20%{transform:translate(-7px,2px)}40%{transform:translate(6px,-2px)}60%{transform:translate(-5px,-1px)}80%{transform:translate(4px,1px)}}
  `;
  document.head.appendChild(style);

  /* ---------- roster / balance ---------- */
  TODDLERS.forEach(character => {
    if (!BASE_ROSTER.includes(character)) BASE_ROSTER.push(character);
    if (!ALL_ROSTER.includes(character)) {
      const i = ALL_ROSTER.indexOf("martin");
      ALL_ROSTER.splice(i >= 0 ? i : ALL_ROSTER.length, 0, character);
    }
  });
  STATS.alice={hp:100,basic:5.5,range:104,recovery:470,specialDamage:12,ultimateDamage:27};
  STATS.leo={hp:100,basic:5.5,range:98,recovery:490,specialDamage:13,ultimateDamage:27};
  STATS.barrett={hp:100,basic:5,range:88,recovery:650,specialDamage:12,ultimateDamage:28};

  const prevName=displayName;
  displayName=function(c){if(c==="alice")return"ALICE";if(c==="leo")return"LEO";if(c==="barrett")return"BARRETT";return prevName(c)};

  function aliceHTML(){return `<div class="bb-toddler alice-model"><div class="bb-alice-hair"></div><div class="bb-toddler-face"><div class="bb-toddler-eye l"></div><div class="bb-toddler-eye r"></div><div class="bb-toddler-mouth"></div></div><div class="bb-alice-shirt"></div><div class="bb-toddler-arm l"></div><div class="bb-toddler-arm r bb-alice-wand-arm"><div class="bb-fairy-wand"></div></div><div class="bb-toddler-leg l"></div><div class="bb-toddler-leg r"></div><div class="bb-toddler-shoe l"></div><div class="bb-toddler-shoe r"></div></div>`}
  function leoHTML(){return `<div class="bb-toddler leo-model"><div class="bb-leo-hair"></div><div class="bb-toddler-face"><div class="bb-toddler-eye l"></div><div class="bb-toddler-eye r"></div><div class="bb-toddler-mouth"></div></div><div class="bb-leo-shirt"></div><div class="bb-toddler-arm l"><div class="bb-dino-claw"></div></div><div class="bb-toddler-arm r"><div class="bb-dino-claw"></div></div><div class="bb-toddler-leg l"></div><div class="bb-toddler-leg r"></div><div class="bb-toddler-shoe l"></div><div class="bb-toddler-shoe r"></div></div>`}
  function barrettHTML(){return `<div class="bb-toddler barrett-model"><div class="bb-barrett-hair"></div><div class="bb-toddler-face"><div class="bb-toddler-eye l"></div><div class="bb-toddler-eye r"></div><div class="bb-toddler-mouth"></div></div><div class="bb-barrett-shirt"></div><div class="bb-toddler-arm l"></div><div class="bb-toddler-arm r"><div class="bb-remote"></div></div><div class="bb-toddler-leg l"></div><div class="bb-toddler-leg r"></div><div class="bb-toddler-shoe l"></div><div class="bb-toddler-shoe r"></div></div>`}

  const prevHTML=characterHTML;
  characterHTML=function(c){if(c==="alice")return aliceHTML();if(c==="leo")return leoHTML();if(c==="barrett")return barrettHTML();return prevHTML(c)};
  const prevSpecialIcon=specialIconHTML,prevUltimateIcon=ultimateIconHTML;
  specialIconHTML=function(c){if(c==="alice")return'<div class="bb-icon-lollipop"></div>';if(c==="leo")return'<div class="bb-icon-foot"></div>';if(c==="barrett")return'<div class="bb-icon-rc"></div>';return prevSpecialIcon(c)};
  ultimateIconHTML=function(c){if(c==="alice")return'<div class="bb-icon-crown"></div>';if(c==="leo")return'<div class="bb-icon-dinohead"></div>';if(c==="barrett")return'<div class="bb-icon-bearwheel"></div>';return prevUltimateIcon(c)};
  if(typeof bbMeleeIconHTML==="function"){const p=bbMeleeIconHTML;bbMeleeIconHTML=function(c){if(c==="alice")return'<div class="bb-icon-wand"></div>';if(c==="leo")return'<div class="bb-icon-claw"></div>';if(c==="barrett")return'<div class="bb-icon-headbutt"></div>';return p(c)}}

  /* ---------- selection cards ---------- */
  const grid=document.querySelector(".fighter-select");
  const cards={alice:["ALICE","Fairy Wand • Grape Lollipop • Fairy Princess"],leo:["LEO","Dino Claws • Dino Stomp • Dino Stampede"],barrett:["BARRETT","Headbutt • RC Car • Bear Driver"]};
  function addCard(c){if(document.querySelector(`.fighter-card[data-character="${c}"]`))return;const b=document.createElement("button");b.className="fighter-card";b.dataset.character=c;b.innerHTML=`<div class="card-model-holder" data-preview="${c}"></div><strong>${cards[c][0]}</strong><small>${cards[c][1]}</small>`;martinCard.before(b)}
  TODDLERS.forEach(addCard);
  function normalizeToddlerSelection(){document.querySelectorAll(".fighter-card").forEach(card=>{card.classList.toggle("p1-selected",card.dataset.character===player1Character);card.classList.toggle("p2-selected",gameMode==="2P"&&card.dataset.character===player2Character)})}
  if(grid)grid.addEventListener("click",e=>{const card=e.target.closest(".fighter-card");if(!card||!TODDLERS.includes(card.dataset.character))return;const c=card.dataset.character;if(gameMode==="1P"){player1Character=c;selectionText.textContent="PLAYER 1: "+displayName(c);mapSelectButton.disabled=false}else if(selectionStage===1){player1Character=c;selectionStage=2;selectionPrompt.textContent="PLAYER 2 — CHOOSE YOUR FIGHTER";selectionText.textContent="PLAYER 1: "+displayName(c)+"  |  PLAYER 2: NOT SELECTED"}else{player2Character=c;selectionText.textContent="PLAYER 1: "+displayName(player1Character)+"  |  PLAYER 2: "+displayName(c);mapSelectButton.disabled=false}setTimeout(normalizeToddlerSelection,0)});

  const toddlerMoves={alice:{melee:"Fairy Wand",special:"Grape Lollipop",ultimate:"Fairy Princess"},leo:{melee:"Dino Claws",special:"Dino Stomp",ultimate:"Dino Stampede"},barrett:{melee:"Headbutt",special:"RC Car",ultimate:"Bear Driver"}};
  function renderToddlerDetail(c){if(!toddlerMoves[c])return;const n=document.getElementById("bbDetailName"),p=document.getElementById("bbDetailPreview"),m=document.getElementById("bbDetailMoves");if(!n||!p||!m)return;n.textContent=displayName(c);p.innerHTML=characterHTML(c);const d=toddlerMoves[c];m.innerHTML=`<div class="bb-detail-move melee"><div class="bb-detail-move-type">MELEE</div><div class="bb-detail-move-name">${d.melee}</div></div><div class="bb-detail-move special"><div class="bb-detail-move-type">SPECIAL</div><div class="bb-detail-move-name">${d.special}</div></div><div class="bb-detail-move ultimate"><div class="bb-detail-move-type">ULTIMATE</div><div class="bb-detail-move-name">${d.ultimate}</div></div>`}
  document.querySelectorAll(".fighter-card").forEach(card=>{if(!TODDLERS.includes(card.dataset.character))return;["mouseenter","focus","click"].forEach(ev=>card.addEventListener(ev,()=>setTimeout(()=>renderToddlerDetail(card.dataset.character),0)))});

  /* ---------- helpers ---------- */
  const toddlerModel=p=>p.fighter.querySelector(".bb-toddler");
  function shakeArena(){arena.classList.remove("bb-toddler-shake");void arena.offsetWidth;arena.classList.add("bb-toddler-shake");setTimeout(()=>arena.classList.remove("bb-toddler-shake"),390)}
  function magicBurst(x,bottom,count=8){for(let i=0;i<count;i++){const s=document.createElement("div");s.className="bb-magic-star";s.style.left=x+"px";s.style.bottom=bottom+"px";s.style.setProperty("--sx",(-34+Math.random()*68)+"px");s.style.setProperty("--sy",(-35+Math.random()*70)+"px");effects.appendChild(s);setTimeout(()=>s.remove(),600)}}
  function dustAt(x,bottom,count=6){for(let i=0;i<count;i++){const d=document.createElement("div");d.className="bb-dust";d.style.left=(x+Math.random()*25)+"px";d.style.bottom=bottom+"px";d.style.setProperty("--dx",(-28+Math.random()*56)+"px");effects.appendChild(d);setTimeout(()=>d.remove(),540)}}
  function inMelee(attacker,target,range){return Math.abs(attacker.x-target.x)<=range&&Math.abs(attacker.y-target.y)<75}

  /* ---------- toddler basics ---------- */
  const prevBasic=basicAttack;
  basicAttack=function(attacker,target){
    if(!TODDLERS.includes(attacker.character))return prevBasic(attacker,target);
    if(!canAct(attacker)||attacker.attackCooldown)return;
    const model=toddlerModel(attacker),stats=STATS[attacker.character];attacker.attackCooldown=true;
    if(attacker.character==="alice"){
      model?.classList.add("bb-alice-basic");
      setTimeout(()=>{if(inMelee(attacker,target,stats.range)){dealDamage(attacker,target,stats.basic,{type:"normal"});magicBurst(target.x+30,105+target.y,7)}},220);
      setTimeout(()=>model?.classList.remove("bb-alice-basic"),440);
    } else if(attacker.character==="leo"){
      let firstHit=false;
      const swipe=(which,delay)=>setTimeout(()=>{if(roundOver)return;model?.classList.add(which);const trail=document.createElement("div");trail.className="bb-claw-trail";trail.style.left=(target.x+(attacker.facing===1?-5:25))+"px";trail.style.bottom=(95+target.y)+"px";effects.appendChild(trail);setTimeout(()=>trail.remove(),300);if(inMelee(attacker,target,stats.range)){const beforeA=attacker.ultimate,beforeT=target.ultimate;dealDamage(attacker,target,stats.basic/2,{type:"normal"});if(firstHit&&!roundOver){attacker.ultimate=Math.max(beforeA,attacker.ultimate-14);target.ultimate=Math.max(beforeT,target.ultimate-7);updateHUD()}firstHit=true}setTimeout(()=>model?.classList.remove(which),250)},delay);
      swipe("bb-leo-swipe1",90);swipe("bb-leo-swipe2",285);
    } else {
      attacker.stunned=true;model?.classList.add("bb-headbutt");const dir=attacker.facing,start=attacker.x;let steps=0;const run=setInterval(()=>{if(roundOver||steps++>=4){clearInterval(run);return}attacker.x+=dir*8;updatePositions()},45);
      setTimeout(()=>{if(roundOver)return;if(inMelee(attacker,target,stats.range+22)){dealDamage(attacker,target,stats.basic,{type:"normal"});if(!roundOver)stunTarget(target,500);shakeArena()}model?.classList.remove("bb-headbutt");model?.classList.add("bb-stumble");attacker.x=Math.max(0,start-dir*10);updatePositions();setTimeout(()=>model?.classList.remove("bb-stumble"),500)},260);
      setTimeout(()=>{attacker.stunned=false},620);
    }
    setTimeout(()=>{attacker.attackCooldown=false;model?.classList.remove("bb-alice-basic","bb-leo-swipe1","bb-leo-swipe2","bb-headbutt","bb-stumble")},stats.recovery);
  };

  /* ---------- specials ---------- */
  function aliceLollipop(attacker,target){
    addComicText("GRAPE LOLLIPOP!","purple-text",1700);const model=toddlerModel(attacker),wand=model?.querySelector(".bb-fairy-wand"),arm=model?.querySelector(".bb-alice-wand-arm");if(wand)wand.style.visibility="hidden";const held=document.createElement("div");held.className="bb-hand-lollipop";arm?.appendChild(held);
    setTimeout(()=>{if(roundOver){held.remove();if(wand)wand.style.visibility="visible";return}held.remove();const ball=document.createElement("div");ball.className="bb-grape-lollipop";let x=attacker.x+(attacker.facing===1?55:-8),dir=attacker.facing;ball.style.left=x+"px";ball.style.bottom=(76+attacker.y)+"px";effects.appendChild(ball);if(wand)setTimeout(()=>wand.style.visibility="visible",120);const loop=setInterval(()=>{if(roundOver||!ball.isConnected){clearInterval(loop);ball.remove();return}x+=12*dir;ball.style.left=x+"px";if(Math.abs((x+20)-(target.x+35))<34&&projectileCanHit(target,"mid")){clearInterval(loop);ball.remove();dealDamage(attacker,target,STATS.alice.specialDamage,{type:"special"});magicBurst(target.x+30,115+target.y,10);return}if(x<-100||x>arena.clientWidth+100){clearInterval(loop);ball.remove()}},28)},420);
    setTimeout(()=>{held.remove();if(wand)wand.style.visibility="visible"},1500);
  }
  function leoStomp(attacker,target){
    addComicText("DINO STOMP!","green-text",1600);const model=toddlerModel(attacker);model?.classList.add("bb-leo-stomp");setTimeout(()=>{if(roundOver)return;const foot=document.createElement("div");foot.className="bb-dino-foot";foot.style.left=(attacker.x+attacker.facing*62-45)+"px";foot.style.bottom="22px";effects.appendChild(foot);const shock=document.createElement("div");shock.className="bb-ground-shock";shock.style.left=(attacker.x+attacker.facing*54-54)+"px";shock.style.bottom="17px";effects.appendChild(shock);dustAt(attacker.x+attacker.facing*55,22,7);if(Math.abs(attacker.x-target.x)<=150&&target.y<55)dealDamage(attacker,target,STATS.leo.specialDamage,{type:"special"});setTimeout(()=>{foot.remove();shock.remove()},500)},430);setTimeout(()=>model?.classList.remove("bb-leo-stomp"),720)
  }
  function barrettRC(attacker,target){
    addComicText("RC RAMPAGE!","red-text",1600);const model=toddlerModel(attacker);model?.classList.add("bb-remote-press");setTimeout(()=>{const car=document.createElement("div");car.className="bb-rc-car";car.innerHTML='<div class="antenna"></div><div class="body"></div><div class="cab"></div><div class="wheel l"></div><div class="wheel r"></div>';const dir=attacker.facing;let x=attacker.x+(dir===1?35:-62),hit=false;car.style.left=x+"px";car.style.bottom="27px";if(dir===-1)car.style.transform="scaleX(-1)";effects.appendChild(car);const loop=setInterval(()=>{if(roundOver||!car.isConnected){clearInterval(loop);car.remove();return}x+=13*dir;car.style.left=x+"px";if(!hit&&Math.abs((x+36)-(target.x+35))<35&&target.y<55){hit=true;dealDamage(attacker,target,STATS.barrett.specialDamage,{type:"special"});dustAt(target.x+25,25,6)}if(x<-100||x>arena.clientWidth+100){clearInterval(loop);car.remove()}},28)},300);setTimeout(()=>model?.classList.remove("bb-remote-press"),550)
  }
  const prevSpecial=specialAttack;
  specialAttack=function(attacker,target){if(!TODDLERS.includes(attacker.character))return prevSpecial(attacker,target);if(!canAct(attacker)||attacker.specialCooldown)return;beginSpecialCooldown(attacker);if(attacker.character==="alice")aliceLollipop(attacker,target);else if(attacker.character==="leo")leoStomp(attacker,target);else barrettRC(attacker,target)};

  /* ---------- ultimates ---------- */
  function addAliceRoyal(model){if(!model)return;if(!model.querySelector(".bb-alice-wings")){const w=document.createElement("div");w.className="bb-alice-wings";model.prepend(w)}if(!model.querySelector(".bb-princess-crown")){const c=document.createElement("div");c.className="bb-princess-crown";model.appendChild(c)}if(!model.querySelector(".bb-alice-glow")){const g=document.createElement("div");g.className="bb-alice-glow";model.prepend(g)}}
  function aliceUltimate(attacker,target){
    actionLock=true;addComicText("FAIRY PRINCESS!","purple-text",2300);const model=toddlerModel(attacker);addAliceRoyal(model);for(let i=0;i<18;i++)setTimeout(()=>{if(roundOver)return;magicBurst(attacker.x+35,100+attacker.y,2)},i*95);
    setTimeout(()=>{if(roundOver)return;const r=arena.getBoundingClientRect(),tr=target.fighter.getBoundingClientRect(),cx=tr.left-r.left+tr.width*.5,cy=tr.top-r.top+tr.height*.48,l=document.createElement("div");l.className="bb-giant-lollipop";const sx=cx+(attacker.facing===1?185:-185),ex=cx-71,sy=-195,ey=Math.max(55,cy-70);l.style.left=sx+"px";l.style.top=sy+"px";effects.appendChild(l);l.animate([{transform:"translate(0,0) rotate(-28deg)"},{transform:`translate(${(ex-sx)*.55}px,${(ey-sy)*.52}px) rotate(18deg)`,offset:.55},{transform:`translate(${ex-sx}px,${ey-sy}px) rotate(34deg)`}],{duration:1320,easing:"cubic-bezier(.22,.62,.28,1)",fill:"forwards"});setTimeout(()=>{if(roundOver)return;dealDamage(attacker,target,STATS.alice.ultimateDamage,{type:"ultimate",ignoreBlock:true});shakeArena();magicBurst(target.x+30,125+target.y,18)},1280);setTimeout(()=>l.remove(),1600)},800);
    setTimeout(()=>{model?.querySelector(".bb-alice-wings")?.remove();model?.querySelector(".bb-princess-crown")?.remove();model?.querySelector(".bb-alice-glow")?.remove();if(!roundOver)actionLock=false},2600)
  }
  function dinoMarkup(kind){if(kind==="triceratops")return'<div class="tail"></div><div class="body"></div><div class="frill"></div><div class="head"></div><div class="horn h1"></div><div class="horn h2"></div><div class="leg a"></div><div class="leg b"></div>';if(kind==="trex")return'<div class="tail"></div><div class="body"></div><div class="head"></div><div class="jaw"></div><div class="tinyarm"></div><div class="leg a"></div><div class="leg b"></div>';return'<div class="clubtail"></div><div class="body"></div><div class="armor"></div><div class="head"></div><div class="leg a"></div><div class="leg b"></div>'}
  function runDino(attacker,target,kind,damage){return new Promise(resolve=>{if(roundOver){resolve();return}const d=document.createElement("div");d.className=`bb-cine-dino bb-${kind}`;d.innerHTML=dinoMarkup(kind);const dir=attacker.facing;let x=dir===1?-205:arena.clientWidth+205,hit=false,after=0;d.style.left=x+"px";d.style.bottom="26px";if(dir===-1)d.style.transform="scaleX(-1)";effects.appendChild(d);const speed=kind==="triceratops"?17.5:kind==="trex"?16.5:15.5;const loop=setInterval(()=>{if(roundOver||!d.isConnected){clearInterval(loop);d.remove();resolve();return}x+=speed*dir;d.style.left=x+"px";if(!hit&&Math.abs((x+90)-(target.x+35))<50){hit=true;dealDamage(attacker,target,damage,{type:"ultimate",ignoreBlock:true});shakeArena();dustAt(target.x+30,28,6);if(kind==="anky")d.querySelector(".clubtail")?.animate([{transform:"rotate(0)"},{transform:"rotate(48deg)"},{transform:"rotate(-18deg)"}],{duration:430,easing:"ease-out"})}if(hit&&++after>18){clearInterval(loop);d.remove();resolve();return}if(x>arena.clientWidth+210||x<-210){clearInterval(loop);d.remove();resolve()}},28)})}
  async function leoUltimate(attacker,target){actionLock=true;addComicText("DINO STAMPEDE!","green-text",2600);await new Promise(r=>setTimeout(r,450));await runDino(attacker,target,"triceratops",8);await new Promise(r=>setTimeout(r,420));await runDino(attacker,target,"trex",9);await new Promise(r=>setTimeout(r,470));await runDino(attacker,target,"anky",10);setTimeout(()=>{if(!roundOver)actionLock=false},350)}
  function bearCarMarkup(){return'<div class="bb-speedline a"></div><div class="bb-speedline b"></div><div class="bb-speedline c"></div><div class="carbody"></div><div class="hood"></div><div class="cab"><div class="bb-bear-head"><div class="bb-bear-eye l"></div><div class="bb-bear-eye r"></div><div class="bb-bear-muzzle"></div></div></div><div class="wheel l"></div><div class="wheel r"></div>'}
  function barrettUltimate(attacker,target){actionLock=true;addComicText("BEAR DRIVER!","red-text",2300);const model=toddlerModel(attacker);model?.classList.add("bb-remote-press");setTimeout(()=>{const car=document.createElement("div");car.className="bb-big-bear-car";car.innerHTML=bearCarMarkup();const dir=attacker.facing;let x=dir===1?-265:arena.clientWidth+265,speed=8,hit=false;car.style.left=x+"px";car.style.bottom="24px";if(dir===-1)car.style.transform="scaleX(-1)";effects.appendChild(car);const loop=setInterval(()=>{if(roundOver||!car.isConnected){clearInterval(loop);car.remove();if(!roundOver)actionLock=false;return}speed=Math.min(19,speed+.55);x+=speed*dir;car.style.left=x+"px";if(!hit&&Math.abs((x+122)-(target.x+35))<62){hit=true;dealDamage(attacker,target,STATS.barrett.ultimateDamage,{type:"ultimate",ignoreBlock:true});shakeArena();dustAt(target.x+30,28,10)}if(x>arena.clientWidth+280||x<-280){clearInterval(loop);car.remove();if(!roundOver)actionLock=false}},28)},760);setTimeout(()=>model?.classList.remove("bb-remote-press"),650);setTimeout(()=>{if(!roundOver)actionLock=false},3400)}
  const prevUltimate=ultimateAttack;
  ultimateAttack=function(attacker,target){if(!TODDLERS.includes(attacker.character))return prevUltimate(attacker,target);if(!canAct(attacker)||attacker.ultimate<100)return;attacker.ultimate=0;updateHUD();if(attacker.character==="alice")aliceUltimate(attacker,target);else if(attacker.character==="leo")leoUltimate(attacker,target);else barrettUltimate(attacker,target)};

  /* ---------- celebrations ---------- */
  function victoryPerson(stage,c,left,extra=""){const h=document.createElement("div");h.className="bb-toddler-victor "+extra;h.style.left=left;h.innerHTML=characterHTML(c);stage.appendChild(h);return h}
  function aliceCelebration(stage){const p=victoryPerson(stage,"alice","50%","bb-alice-twirl"),m=p.querySelector(".alice-model");addAliceRoyal(m);for(let i=0;i<32;i++)setTimeout(()=>{if(stage.isConnected)magicBurst(100+Math.random()*(arena.clientWidth-200),80+Math.random()*170,1)},i*100);setTimeout(()=>{if(!stage.isConnected)return;const l=document.createElement("div");l.className="bb-victory-lollipop";stage.appendChild(l)},2100)}
  function leoCelebration(stage){victoryPerson(stage,"leo","40%","bb-leo-victor");const r=document.createElement("div");r.className="bb-baby-trex";r.innerHTML='<div class="tail"></div><div class="body"></div><div class="head"></div><div class="jaw"></div><div class="leg a"></div><div class="leg b"></div>';stage.appendChild(r)}
  function barrettCelebration(stage){const car=document.createElement("div");car.className="bb-celeb-car";car.innerHTML='<div class="carbody"></div><div class="cab"><div class="bb-celeb-bear"><div class="bb-bear-head"><div class="bb-bear-eye l"></div><div class="bb-bear-eye r"></div><div class="bb-bear-muzzle"></div></div></div><div class="bb-celeb-barrett">'+barrettHTML()+'</div><div class="bb-king-crown"></div></div><div class="wheel l"></div><div class="wheel r"></div>';stage.appendChild(car)}
  function celebrateToddler(winner){const stage=document.createElement("div");stage.className="bb-toddler-victory";effects.appendChild(stage);const b=document.createElement("div");b.className="bb-toddler-banner";b.textContent=displayName(winner.character)+" WINS THE MATCH!";stage.appendChild(b);if(winner.character==="alice")aliceCelebration(stage);else if(winner.character==="leo")leoCelebration(stage);else barrettCelebration(stage);return stage}
  const prevFinish=finishRound;
  finishRound=function(winner){if(!TODDLERS.includes(winner.character))return prevFinish(winner);roundOver=true;fightStarted=false;actionLock=true;if(winner===P1)player1Wins++;else player2Wins++;roundScore.textContent=player1Wins+" - "+player2Wins;winnerText.textContent=displayName(winner.character)+" WINS ROUND "+currentRound;const matchWon=player1Wins>=2||player2Wins>=2;if(matchWon){player1Fighter.classList.add("bb-final-ko-cleared");player2Fighter.classList.add("bb-final-ko-cleared")}setTimeout(()=>{if(!matchWon){koOverlay.classList.remove("hidden");matchStatus.textContent=player1Wins+" - "+player2Wins;setTimeout(()=>{currentRound++;koOverlay.classList.add("hidden");startRound()},1450);return}gameOver=true;matchActive=false;koOverlay.classList.add("hidden");const stage=celebrateToddler(winner);setTimeout(()=>{stage.remove();koOverlay.classList.remove("hidden");winnerText.textContent=displayName(winner.character)+" WINS!";if(challengeMode&&player1Wins>=2){challengeResult="won";unlockMartin();matchStatus.textContent="MARTIN DEFEATED — MARTIN UNLOCKED";newGameButton.textContent="CONTINUE";newGameButton.classList.remove("hidden");return}if(challengeMode&&player2Wins>=2){challengeResult="lost";matchStatus.textContent="MARTIN WINS — TRY AGAIN";newGameButton.textContent="TRY AGAIN";newGameButton.classList.remove("hidden");return}matchStatus.textContent=displayName(winner.character)+" WINS THE MATCH";newGameButton.textContent="NEW GAME";newGameButton.classList.remove("hidden")},5000)},900)};

  renderPreviews();
  generateTitleMatchup();
  normalizeToddlerSelection();
  if(typeof bbRefreshMeleeHud==="function")bbRefreshMeleeHud();
})();